-- Primary schema migration for Razk Automation.
-- Run from the project root with:
-- mysql -u root -p < server/database/schema.sql
--
-- The canonical schema is kept in server/database/schema.sql so it can be
-- used by local setup, CI, and production provisioning without drift.
