const fs = require("fs");
const path = require("path");
const ExcelJS = require("exceljs");

const logoPath = path.join(__dirname, "..", "assets", "hya-logo.png");

const formatDate = (value) => {
  if (!value) return "-";
  return new Intl.DateTimeFormat("en-IN", {
    timeZone: "Asia/Kolkata",
    day: "2-digit",
    month: "short",
    year: "numeric"
  }).format(new Date(value));
};

const formatTime = (value) => {
  if (!value) return "-";
  return new Intl.DateTimeFormat("en-IN", {
    timeZone: "Asia/Kolkata",
    hour: "2-digit",
    minute: "2-digit"
  }).format(new Date(value));
};

const formatDateTime = (value = new Date()) =>
  new Intl.DateTimeFormat("en-IN", {
    timeZone: "Asia/Kolkata",
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  }).format(new Date(value));

const gpsText = (lat, lng, status) => {
  if (lat !== "" && lat !== null && lat !== undefined && lng !== "" && lng !== null && lng !== undefined) {
    return `${lat}, ${lng}`;
  }
  return status || "Location not available";
};

const setColumnWidths = (sheet, widths) => {
  sheet.columns = widths.map((width) => ({ width }));
};

const styleTitleBlock = (sheet) => {
  sheet.getRow(1).height = 28;
  sheet.getRow(2).height = 22;
  sheet.getCell("B1").font = { bold: true, color: { argb: "FF0F172A" }, size: 16 };
  sheet.getCell("B2").font = { bold: true, color: { argb: "FF1D4ED8" }, size: 12 };
  sheet.getCell("B3").font = { color: { argb: "FF64748B" }, size: 9 };
};

const addLogo = (workbook, sheet) => {
  if (!fs.existsSync(logoPath)) return;
  const imageId = workbook.addImage({
    buffer: fs.readFileSync(logoPath),
    extension: "png"
  });
  sheet.addImage(imageId, {
    tl: { col: 0.1, row: 0.15 },
    ext: { width: 58, height: 58 }
  });
};

const addHeader = (workbook, sheet, report, endColumn = "L") => {
  sheet.mergeCells(`B1:${endColumn}1`);
  sheet.mergeCells(`B2:${endColumn}2`);
  sheet.mergeCells(`B3:${endColumn}3`);
  sheet.getCell("B1").value = "HYA Tech Employee Management System";
  sheet.getCell("B2").value = report.title || "Attendance Report";
  sheet.getCell("B3").value = `Generated on: ${formatDateTime(report.generatedAt)} | Generated by: ${
    report.generatedBy?.name || "-"
  } (${report.generatedBy?.role || "-"})`;
  styleTitleBlock(sheet);
  addLogo(workbook, sheet);
};

const styleSectionTitle = (cell) => {
  cell.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 11 };
  cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1D4ED8" } };
  cell.alignment = { vertical: "middle" };
};

const styleTableHeader = (row) => {
  row.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 9 };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F3B66" } };
    cell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
    cell.border = {
      top: { style: "thin", color: { argb: "FF93C5FD" } },
      left: { style: "thin", color: { argb: "FF93C5FD" } },
      bottom: { style: "thin", color: { argb: "FF93C5FD" } },
      right: { style: "thin", color: { argb: "FF93C5FD" } }
    };
  });
};

const styleDataRow = (row, index) => {
  row.eachCell((cell) => {
    cell.font = { color: { argb: "FF0F172A" }, size: 9 };
    cell.alignment = { vertical: "middle", wrapText: true };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: index % 2 === 0 ? "FFF8FAFC" : "FFFFFFFF" }
    };
    cell.border = {
      top: { style: "thin", color: { argb: "FFE2E8F0" } },
      left: { style: "thin", color: { argb: "FFE2E8F0" } },
      bottom: { style: "thin", color: { argb: "FFE2E8F0" } },
      right: { style: "thin", color: { argb: "FFE2E8F0" } }
    };
  });
};

const addKeyValueRows = (sheet, startRow, title, rows) => {
  sheet.mergeCells(`A${startRow}:L${startRow}`);
  styleSectionTitle(sheet.getCell(`A${startRow}`));
  sheet.getCell(`A${startRow}`).value = title;
  let rowNumber = startRow + 1;
  rows.forEach(([labelA, valueA, labelB, valueB]) => {
    const row = sheet.getRow(rowNumber);
    row.values = [labelA, valueA ?? "-", "", "", "", "", labelB || "", valueB ?? "-"];
    row.getCell(1).font = { bold: true, color: { argb: "FF475569" } };
    row.getCell(7).font = { bold: true, color: { argb: "FF475569" } };
    rowNumber += 1;
  });
  return rowNumber + 1;
};

const addSummaryRows = (sheet, startRow, summary = {}) =>
  addKeyValueRows(sheet, startRow, "Attendance Summary", [
    ["Present", summary.present || 0, "Absent", summary.absent || 0],
    ["Late", summary.late || 0, "Half Day", summary.halfDay || 0],
    ["Leave", summary.leave || 0, "Week Off", summary.weekOff || 0],
    ["Working Hours", summary.totalWorkingHours || 0, "Attendance %", `${summary.attendancePercentage ?? "-"}%`]
  ]);

const addEmployeeReportSheet = (workbook, report) => {
  const sheet = workbook.addWorksheet("Daily Attendance", {
    pageSetup: { orientation: "landscape", fitToPage: true, fitToWidth: 1, fitToHeight: 0 }
  });
  sheet.views = [{ state: "frozen", ySplit: 11 }];
  setColumnWidths(sheet, [14, 11, 14, 14, 18, 15, 18, 24, 24, 12, 14, 34]);
  addHeader(workbook, sheet, report, "L");

  let nextRow = addKeyValueRows(sheet, 5, "Employee Details", [
    ["Employee ID", report.employee?.employeeId, "Name", report.employee?.name],
    ["Department", report.employee?.department, "Designation", report.employee?.designation],
    ["Joining Date", report.employee?.joiningDate ? formatDate(report.employee.joiningDate) : "-", "Date Range", `${formatDate(report.from)} to ${formatDate(report.to)}`]
  ]);
  nextRow = addSummaryRows(sheet, nextRow, report.summary);

  const headerRow = sheet.getRow(nextRow);
  headerRow.values = [
    "Date",
    "Day",
    "Check-in",
    "Check-out",
    "Shift",
    "Working Hours",
    "Status",
    "Check-in Location",
    "Check-out Location",
    "Accuracy",
    "Code",
    "Remarks"
  ];
  styleTableHeader(headerRow);

  report.records.forEach((record, index) => {
    const row = sheet.getRow(nextRow + 1 + index);
    row.values = [
      formatDate(record.date),
      record.day,
      formatTime(record.checkIn),
      formatTime(record.checkOut),
      record.shiftName || "Not marked",
      Number(record.workingHours || 0),
      record.status,
      gpsText(record.checkInLatitude, record.checkInLongitude, record.checkInLocationStatus),
      gpsText(record.checkOutLatitude, record.checkOutLongitude, record.checkOutLocationStatus),
      record.checkInAccuracy || record.checkOutAccuracy || "-",
      record.statusCode,
      record.remarks || "-"
    ];
    styleDataRow(row, index);
  });

  const footerRow = nextRow + 2 + report.records.length;
  sheet.mergeCells(`A${footerRow}:D${footerRow}`);
  sheet.mergeCells(`E${footerRow}:H${footerRow}`);
  sheet.mergeCells(`I${footerRow}:L${footerRow}`);
  sheet.getCell(`A${footerRow}`).value = "Prepared by";
  sheet.getCell(`E${footerRow}`).value = "HR Manager Signature";
  sheet.getCell(`I${footerRow}`).value = "Authorized Signature";
  [sheet.getCell(`A${footerRow}`), sheet.getCell(`E${footerRow}`), sheet.getCell(`I${footerRow}`)].forEach((cell) => {
    cell.font = { bold: true, color: { argb: "FF475569" } };
    cell.border = { top: { style: "medium", color: { argb: "FF94A3B8" } } };
    cell.alignment = { horizontal: "center" };
  });
};

const addSummaryReportSheet = (workbook, report) => {
  const sheet = workbook.addWorksheet("Attendance Summary", {
    pageSetup: { orientation: "landscape", fitToPage: true, fitToWidth: 1, fitToHeight: 0 }
  });
  sheet.views = [{ state: "frozen", ySplit: 9 }];
  setColumnWidths(sheet, [8, 16, 24, 18, 20, 10, 10, 10, 10, 10, 14, 14]);
  addHeader(workbook, sheet, report, "L");

  let nextRow = addKeyValueRows(sheet, 5, "Report Details", [
    ["Report Type", report.type, "Date Range", `${formatDate(report.from)} to ${formatDate(report.to)}`],
    ["Department", report.department || "All", "Employees", report.rows?.length || 0]
  ]);

  const headerRow = sheet.getRow(nextRow);
  headerRow.values = [
    "S.No",
    "Employee ID",
    "Employee Name",
    "Department",
    "Designation",
    "Present",
    "Absent",
    "Late",
    "Half Day",
    "Leave",
    "Hours",
    "Attendance %"
  ];
  styleTableHeader(headerRow);

  report.rows.forEach((item, index) => {
    const row = sheet.getRow(nextRow + 1 + index);
    row.values = [
      index + 1,
      item.employee?.employeeId || "-",
      item.employee?.name || "-",
      item.employee?.department || "-",
      item.employee?.designation || "-",
      item.summary?.present || 0,
      item.summary?.absent || 0,
      item.summary?.late || 0,
      item.summary?.halfDay || 0,
      item.summary?.leave || 0,
      item.summary?.totalWorkingHours || 0,
      `${item.summary?.attendancePercentage ?? "-"}%`
    ];
    styleDataRow(row, index);
  });

  const legendRow = nextRow + 3 + report.rows.length;
  sheet.mergeCells(`A${legendRow}:L${legendRow}`);
  sheet.getCell(`A${legendRow}`).value = "Legend: P - Present | A - Absent | L - Late | HD - Half Day | LV - Leave | OD - On Duty | WO - Week Off";
  sheet.getCell(`A${legendRow}`).font = { bold: true, color: { argb: "FF475569" } };

  const detailSheet = workbook.addWorksheet("Daily Details", {
    pageSetup: { orientation: "landscape", fitToPage: true, fitToWidth: 1, fitToHeight: 0 }
  });
  detailSheet.views = [{ state: "frozen", ySplit: 1 }];
  setColumnWidths(detailSheet, [16, 24, 14, 10, 14, 14, 18, 14, 12, 28, 28, 32]);
  const detailHeader = detailSheet.getRow(1);
  detailHeader.values = [
    "Employee ID",
    "Employee Name",
    "Date",
    "Day",
    "Check-in",
    "Check-out",
    "Shift",
    "Status",
    "Hours",
    "Check-in Location",
    "Check-out Location",
    "Remarks"
  ];
  styleTableHeader(detailHeader);
  let rowNumber = 2;
  report.rows.forEach((item) => {
    (item.records || []).forEach((record) => {
      const row = detailSheet.getRow(rowNumber);
      row.values = [
        item.employee?.employeeId || "-",
        item.employee?.name || "-",
        formatDate(record.date),
        record.day,
        formatTime(record.checkIn),
        formatTime(record.checkOut),
        record.shiftName || "Not marked",
        record.status,
        Number(record.workingHours || 0),
        gpsText(record.checkInLatitude, record.checkInLongitude, record.checkInLocationStatus),
        gpsText(record.checkOutLatitude, record.checkOutLongitude, record.checkOutLocationStatus),
        record.remarks || "-"
      ];
      styleDataRow(row, rowNumber);
      rowNumber += 1;
    });
  });
};

const sendReportExcel = async (res, report, filename) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "HYA Tech HRMS";
  workbook.created = new Date();
  workbook.modified = new Date();

  if (report.type === "employee") addEmployeeReportSheet(workbook, report);
  else addSummaryReportSheet(workbook, report);

  res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  await workbook.xlsx.write(res);
  res.end();
};

module.exports = {
  sendReportExcel
};
